### ISSUE TITLE
Alpha Milestones for 1.0.0

### ISSUE THREAD

**Issue by Stehfyn** [Stehfyn/mcctt#3]
## High Priority
- [ ] Performant manual screen capture (but designed with future automation driven by computer vision in mind)
- [ ] Deterministic association between carnage reports, theater files, and optionally screen capture (.mov <=> .xml <=> .mp4)
- [ ] File format that represents deterministic association and its basic file management
- [ ] Two-step carnage report compression and stat accumulation
- [ ] Async task execution/synchronization and thread pooling
- [ ] Preliminary framework for persistent user settings
- [ ] Debug log sinking to disk and console with appropriate log levels
## Medium Priority
- [ ] Set up a precompiled header to keep build times as low as possible (sooner than later pls)
- [ ] Basic ui for associated captures and a basic video player
- [ ] Basic ui for carnage report screens
- [ ] Document how-tos, caveats, and features
- [ ] Basic profiling
## Low Priority and Beta Milestones
- [ ] Optical character recognition for basic match chronology tracking
- [ ] Dynamic texture atlas generator which drives asset decoding and allocation
- [ ] Make building toolchain and vc++ project user-friendly (Possibly throw on CI/CD as well)
- [ ] Architecture and code documentation
- [ ] Issue templates and smoke tests
- [ ] libmcctt? 👀 If so, finish shared precompiled header premake customization

(You can do this 💪)
